#!/usr/bin/env python3
"""Generate a PyScript filesystem TOML from complete source roots.

Source mappings use ``SOURCE=DESTINATION``. Files are mapped recursively and
preserve their path relative to SOURCE. Only Python source is mounted because
these producer TOMLs describe importable runtime payloads.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path, PurePosixPath

IGNORED_NAMES = {"__pycache__", "build", "dist"}
IGNORED_SUFFIXES = {".pyc", ".pyo"}


def parse_mapping(value: str) -> tuple[Path, PurePosixPath]:
    try:
        source, destination = value.split("=", 1)
    except ValueError as exc:
        raise argparse.ArgumentTypeError("mapping must be SOURCE=DESTINATION") from exc
    if not source or not destination.startswith("/"):
        raise argparse.ArgumentTypeError(
            "mapping must have a non-empty source and an absolute destination"
        )
    return Path(source), PurePosixPath(destination)


def include_file(path: Path) -> bool:
    return (
        path.suffix == ".py"
        and not any(part.startswith(".") or part in IGNORED_NAMES for part in path.parts)
        and path.suffix.lower() not in IGNORED_SUFFIXES
    )


def raw_url(repository: str, ref: str, path: Path) -> str:
    return f"https://raw.githubusercontent.com/{repository}/{ref}/{path.as_posix()}"


def repository_path(path: Path) -> Path:
    if path.is_absolute() or ".." in path.parts:
        raise SystemExit(f"source mappings must be repository-relative: {path}")
    return path


def find_ignored_paths(repository_root: Path, paths: list[Path]) -> set[Path]:
    if not paths or not (repository_root / ".git").exists():
        return set()
    try:
        proc = subprocess.run(
            ["git", "check-ignore", "--stdin"],
            input="\n".join(p.as_posix() for p in paths),
            text=True,
            cwd=repository_root,
            capture_output=True,
        )
        if proc.returncode in (0, 1):
            return {Path(line.strip()) for line in proc.stdout.splitlines() if line.strip()}
    except Exception:
        pass
    return set()


def render(
    repository: str,
    ref: str,
    repository_root: Path,
    source_mappings: list[tuple[Path, PurePosixPath]],
    file_mappings: list[tuple[Path, PurePosixPath]],
) -> str:
    destinations: dict[str, str] = {}

    def add(source: Path, destination: PurePosixPath) -> None:
        source_url = raw_url(repository, ref, source)
        destination_text = destination.as_posix()
        previous = destinations.get(destination_text)
        if previous and previous != source_url:
            raise SystemExit(
                f"duplicate PyScript destination {destination_text}: {previous} and {source_url}"
            )
        destinations[destination_text] = source_url

    candidates: list[tuple[Path, PurePosixPath]] = []
    for source_root, destination_root in source_mappings:
        source_root = repository_path(source_root)
        source_root_on_disk = repository_root / source_root
        if not source_root_on_disk.is_dir():
            raise SystemExit(f"source root does not exist: {source_root}")
        for source_on_disk in sorted(source_root_on_disk.rglob("*.py")):
            relative = source_on_disk.relative_to(source_root_on_disk)
            if (
                source_on_disk.is_file()
                and not source_on_disk.is_symlink()
                and include_file(relative)
            ):
                candidates.append((source_root / relative, destination_root / PurePosixPath(relative.as_posix())))

    ignored = find_ignored_paths(repository_root, [c[0] for c in candidates])
    for src, dst in candidates:
        if src not in ignored:
            add(src, dst)

    for source, destination in file_mappings:
        source = repository_path(source)
        source_on_disk = repository_root / source
        if (
            not source_on_disk.is_file()
            or source_on_disk.is_symlink()
            or not include_file(source)
        ):
            raise SystemExit(f"mapped runtime file does not exist or is not Python source: {source}")
        add(source, destination)

    lines = [
        "# Generated by PyDevices publishing automation. Do not edit by hand.",
        "# Sources intentionally track the main branch for the PyScript gallery.",
        "",
        "[files]",
    ]
    for destination, source_url in sorted(destinations.items()):
        lines.append(f"{json.dumps(source_url)} = {json.dumps(destination)}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repository", required=True, help="GitHub OWNER/REPOSITORY")
    parser.add_argument("--repository-root", default=Path("."), type=Path)
    parser.add_argument("--ref", default="main")
    parser.add_argument("--source", action="append", type=parse_mapping, default=[])
    parser.add_argument("--file", action="append", type=parse_mapping, default=[])
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    if not args.source and not args.file:
        parser.error("at least one --source or --file mapping is required")
    content = render(
        args.repository,
        args.ref,
        args.repository_root.resolve(),
        args.source,
        args.file,
    )
    if args.check:
        existing = args.output.read_text() if args.output.exists() else ""
        if existing != content:
            print(f"stale generated PyScript TOML: {args.output}", file=sys.stderr)
            raise SystemExit(1)
        return
    args.output.write_text(content)


if __name__ == "__main__":
    main()
